FROM node:22.18.0-alpine AS Builder

WORKDIR /app

COPY . .

RUN corepack enable

RUN pnpm install --filter @ideaslab/server...

RUN pnpm build --filter=@ideaslab/server...

RUN apk add --no-cache tzdata && ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

WORKDIR /app/apps/server

CMD ["pnpm", "start"]